### ISSUE TITLE
Provide style guidance for highlighting areas of screenshots

### ISSUE THREAD

**Issue by nadrummond** [n3oltd/support#15]
Hi @rn3o,

This is a bit nit picky but I figured if we can decide early on makes it easier for @aroojarshad12.

At the moment in the docs we highlight menu items, buttons etc. with a fairly thick black rectangle with a drop shadow effect:

![image](https://github.com/n3oltd/support/assets/22136493/f593906a-1797-4489-8244-ee0624eb040e)

This is a bit ugly and also "heavy" in that it is quite dominant on the screenshot.

Can you please provide a sample of a nice way to do this based on what others do, what works for us, and what's in accordance with N3O / app branding? A random Google search turns up lots of alternatives, e.g. a click radius circle that is a bit transparent to highlight the area in a less prominent way.

![image](https://github.com/n3oltd/support/assets/22136493/0df640a7-0ecd-4fdd-90b1-c6f059718a1b)

I'm not suggesting this particular design (was just random Google result) but to give example of what I mean at looking at something a bit more elegant.

If you can also liaise please @rn3o with @aroojarshad12 to configure the settings for this in the screen capture software she uses so is minimum effort.

**Comment by rn3o** [comment]
Can we simply make this:
(A) small red arrow (see images below) So it won’t obstruct the screenshot area too much while still getting enough attention?
Or 
(B) a rectangle with thin lines (0.5 or 1px) and make it a bit rounded so it matches the overall UI.

These screenshots should have some padding with light grey background to contain the screenshot, otherwise the cropped screenshot white area will blend with documentation page. Is that possible with Camtasia @aroojarshad12 

Also for GIF/video recording, I would recommend using https://screen.studio
It has capability like auto zoom, custom cursor size and cursor smooth movement without much editing.
There are some nice demo on the website.


![Frame 38](https://github.com/n3oltd/support/assets/98315488/65143970-f960-420a-858e-9ad00015dc2f)
![Frame 37](https://github.com/n3oltd/support/assets/98315488/34a841b6-f560-4c7c-9538-be9a9549b1ba)


Let me know what you think. @aroojarshad12 @nadrummond

**Comment by aroojarshad12** [comment]
@rn3o @nadrummond In my opinion, we can consider "option B" i.e. rounded rectangle with thin lines to highlight. Also, screen studio is for macOS, I have windows.  
For screenshots, I use Snagit which Camtasia offers. Snagit contains visual effects that does not have a padding effect.

**Comment by nadrummond** [comment]
Hi @rn3o,

 A couple of things:
 
 (a) Is there a Windows equivalent of https://screen.studio/? The animated GIF screen recording on their homepage looks really great. Not sure if it's handcrafted but if not, would be really good to find something like that.
 
 (b) For the annotations to the images, I was thinking we should do these with CSS. That way we can ensure consistent styling and also if we do in future update the style, it would automatically apply across the site. The CSS could also do the padding and background.
 
 Is it possible for you Ryan to put some examples together. Ideally something like:
 
```
 <div> <!-- wrapper with whatever styling -->
  <img src="foo.png">
  <div style="..."></div> <!-- some css to do first annotation, e.q. square semi-transparent highlight -->
  <!-- could add additional here -->
 </div>
```

If we can do this using primarily inline styles (failing that classes) we could wrap the whole thing in a component that Arooj can use, e.g.

```
<Screenshot src="foo.png">
  <SquareHighlight x=100, y=200, height=200, width=200 />
</Screenshot>
```

Hopefully makes sense.

**Comment by rn3o** [comment]
Regarding the guideline, @nadrummond are we okay with one of the above options (thin red outline or small red arrow)?

Because this seems to be holding @aroojarshad12 with producing the screenshots from what I hear in this morning meeting.

**Comment by aroojarshad12** [comment]
@nadrummond I used Jumpshare and noticed that for highlighting the outline is quite thick like before, so I will be using Snagit for highlighting using a thin red outline.
